// ============================================================================
// 霜语者冷笑话库（2026-08-21 用户需求）
//   环世界梗 + 冰鹅族主题 + 经典冷笑话，共 356 条（自汇编整理；
//   网络素材仅有标题不可用，正文为按环世界/冰鹅风格创作的汇编）。
//   GameComponent_BinguinDiplomacy 每 10 天（600000 tick）随机讲一条。
// ============================================================================
// ★ 2026-09：356 条笑话正文已全部抽到 Languages/<语言>/Keyed/Binguin.xml
//   （键名 Binguin_Jokes_001…），代码里只留键 → 谁都能翻译/替换文案。
//   改文案请改词条文件，不要在代码里直接写中文。

using Verse;

namespace Binguin.Feature.Band
{
    public static class BinguinJokeLibrary
    {
        public static readonly string[] Jokes = new string[]
        {
            // ---------- 一、环世界梗 ----------
            "Binguin_Jokes_01".Translate(),
            "Binguin_Jokes_02".Translate(),
            "Binguin_Jokes_58".Translate(),
            "Binguin_Jokes_03".Translate(),
            "Binguin_Jokes_04".Translate(),
            "Binguin_Jokes_59".Translate(),
            "Binguin_Jokes_127".Translate(),
            "Binguin_Jokes_05".Translate(),
            "Binguin_Jokes_06".Translate(),
            "Binguin_Jokes_60".Translate(),
            "Binguin_Jokes_61".Translate(),
            "Binguin_Jokes_07".Translate(),
            "Binguin_Jokes_08".Translate(),
            "Binguin_Jokes_62".Translate(),
            "Binguin_Jokes_09".Translate(),
            "Binguin_Jokes_10".Translate(),
            "Binguin_Jokes_74".Translate(),
            "Binguin_Jokes_63".Translate(),
            "Binguin_Jokes_64".Translate(),
            "Binguin_Jokes_75".Translate(),
            "Binguin_Jokes_11".Translate(),
            "Binguin_Jokes_65".Translate(),
            "Binguin_Jokes_66".Translate(),
            "Binguin_Jokes_12".Translate(),
            "Binguin_Jokes_67".Translate(),
            "Binguin_Jokes_76".Translate(),
            "Binguin_Jokes_13".Translate(),
            "Binguin_Jokes_14".Translate(),
            "Binguin_Jokes_15".Translate(),
            "Binguin_Jokes_128".Translate(),
            "Binguin_Jokes_16".Translate(),
            "Binguin_Jokes_17".Translate(),
            "Binguin_Jokes_68".Translate(),
            "Binguin_Jokes_18".Translate(),
            "Binguin_Jokes_129".Translate(),
            "Binguin_Jokes_19".Translate(),
            "Binguin_Jokes_20".Translate(),
            "Binguin_Jokes_69".Translate(),
            "Binguin_Jokes_21".Translate(),
            "Binguin_Jokes_77".Translate(),
            "Binguin_Jokes_130".Translate(),
            "Binguin_Jokes_22".Translate(),
            "Binguin_Jokes_23".Translate(),
            "Binguin_Jokes_24".Translate(),
            "Binguin_Jokes_25".Translate(),
            "Binguin_Jokes_131".Translate(),
            "Binguin_Jokes_26".Translate(),
            "Binguin_Jokes_27".Translate(),
            "Binguin_Jokes_70".Translate(),
            // ---------- 二、冰鹅族/企鹅/冰原主题 ----------
            "Binguin_Jokes_78".Translate(),
            "Binguin_Jokes_79".Translate(),
            "Binguin_Jokes_132".Translate(),
            "Binguin_Jokes_80".Translate(),
            "Binguin_Jokes_81".Translate(),
            "Binguin_Jokes_28".Translate(),
            "Binguin_Jokes_133".Translate(),
            "Binguin_Jokes_82".Translate(),
            "Binguin_Jokes_83".Translate(),
            "Binguin_Jokes_84".Translate(),
            "Binguin_Jokes_85".Translate(),
            "Binguin_Jokes_86".Translate(),
            "Binguin_Jokes_87".Translate(),
            "Binguin_Jokes_88".Translate(),
            "Binguin_Jokes_134".Translate(),
            "Binguin_Jokes_135".Translate(),
            "Binguin_Jokes_89".Translate(),
            "Binguin_Jokes_136".Translate(),
            "Binguin_Jokes_90".Translate(),
            "Binguin_Jokes_91".Translate(),
            "Binguin_Jokes_29".Translate(),
            "Binguin_Jokes_92".Translate(),
            "Binguin_Jokes_30".Translate(),
            "Binguin_Jokes_93".Translate(),
            "Binguin_Jokes_94".Translate(),
            "Binguin_Jokes_95".Translate(),
            "Binguin_Jokes_96".Translate(),
            "Binguin_Jokes_97".Translate(),
            // ---------- 三、环世界日常+问答冷笑话 ----------
            "Binguin_Jokes_31".Translate(),
            "Binguin_Jokes_98".Translate(),
            "Binguin_Jokes_32".Translate(),
            "Binguin_Jokes_99".Translate(),
            "Binguin_Jokes_100".Translate(),
            "Binguin_Jokes_137".Translate(),
            "Binguin_Jokes_101".Translate(),
            "Binguin_Jokes_33".Translate(),
            "Binguin_Jokes_34".Translate(),
            "Binguin_Jokes_138".Translate(),
            "Binguin_Jokes_35".Translate(),
            "Binguin_Jokes_102".Translate(),
            "Binguin_Jokes_36".Translate(),
            "Binguin_Jokes_103".Translate(),
            "Binguin_Jokes_139".Translate(),
            "Binguin_Jokes_104".Translate(),
            "Binguin_Jokes_105".Translate(),
            "Binguin_Jokes_37".Translate(),
            "Binguin_Jokes_106".Translate(),
            "Binguin_Jokes_107".Translate(),
            "Binguin_Jokes_38".Translate(),
            "Binguin_Jokes_39".Translate(),
            "Binguin_Jokes_108".Translate(),
            "Binguin_Jokes_40".Translate(),
            "Binguin_Jokes_71".Translate(),
            "Binguin_Jokes_41".Translate(),
            "Binguin_Jokes_109".Translate(),
            "Binguin_Jokes_42".Translate(),
            "Binguin_Jokes_110".Translate(),
            "Binguin_Jokes_111".Translate(),
            "Binguin_Jokes_112".Translate(),
            "Binguin_Jokes_43".Translate(),
            "Binguin_Jokes_44".Translate(),
            "Binguin_Jokes_113".Translate(),
            // ---------- 四、通用冷笑话 ----------
            "Binguin_Jokes_45".Translate(),
            "Binguin_Jokes_46".Translate(),
            "Binguin_Jokes_114".Translate(),
            "Binguin_Jokes_115".Translate(),
            "Binguin_Jokes_47".Translate(),
            "Binguin_Jokes_48".Translate(),
            "Binguin_Jokes_116".Translate(),
            "Binguin_Jokes_49".Translate(),
            "Binguin_Jokes_72".Translate(),
            "Binguin_Jokes_50".Translate(),
            "Binguin_Jokes_51".Translate(),
            "Binguin_Jokes_117".Translate(),
            "Binguin_Jokes_118".Translate(),
            "Binguin_Jokes_119".Translate(),
            "Binguin_Jokes_120".Translate(),
            "Binguin_Jokes_140".Translate(),
            "Binguin_Jokes_121".Translate(),
            "Binguin_Jokes_52".Translate(),
            "Binguin_Jokes_122".Translate(),
            "Binguin_Jokes_123".Translate(),
            "Binguin_Jokes_141".Translate(),
            "Binguin_Jokes_124".Translate(),
            "Binguin_Jokes_53".Translate(),
            "Binguin_Jokes_142".Translate(),
            "Binguin_Jokes_125".Translate(),
            "Binguin_Jokes_143".Translate(),
            "Binguin_Jokes_144".Translate(),
            "Binguin_Jokes_145".Translate(),
            "Binguin_Jokes_126".Translate(),
            "Binguin_Jokes_54".Translate(),
            "Binguin_Jokes_55".Translate(),
            "Binguin_Jokes_56".Translate(),
            "Binguin_Jokes_73".Translate(),
            "Binguin_Jokes_57".Translate(),
        };
    }
}
